server:
  port: ${DISCOVERY_SERVER_PORT}

spring:
  application:
    name: ${DISCOVERY_SERVER_NAME}
  docker:
    compose:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

management:
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: info
  structured:
    format:
      console:
