server:
  port: ${URL_SHORTENER_PORT}

spring:
  application:
    name: ${URL_SHORTENER_NAME}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DB_NAME:dbname}
    username: ${POSTGRES_USERNAME:test}
    password: ${POSTGRES_PASSWORD:test}
#  sql:
#    init:
#      schema-locations: classpath*:db/postgres/schema.sql
#      data-locations: classpath*:db/postgres/data.sql
#      mode: always
  docker:
    compose:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    enabled: true
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

management:
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: info
  structured:
    format:
      console:
