server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: ${CONFIG_SERVER_NAME:config-server}
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:configs
        git:
          uri: ${GIT_URL}
          clone-on-start: true
          default-label: ${GIT_DEFAULT_LABEL:master}
  docker:
    compose:
      enabled: false

management:
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: info
  structured:
    format:
      console:
